# Generated by Django 3.2.18 on 2025-04-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('hora_recepcion', models.TimeField()),
                ('entidad_emisora', models.CharField(max_length=255)),
                ('numero_expediente', models.CharField(max_length=100)),
                ('dirigido_a', models.CharField(max_length=255)),
                ('recepcionista', models.CharField(choices=[('amanda', 'Amanda González'), ('wanda', 'Wanda Pastor')], max_length=10)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
